steps:
  - label: ":arrow_up: upload all artifacts"
    command: "script.sh"
    artifact_paths: "artifacts/*"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
  - label: ":arrow_up: upload duplicate artifact"
    command: "script.sh"
    artifact_paths: "artifacts/duplicate.txt"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
  - wait: ~
  - label: ":mag: search uploaded artifacts"
    command: "search.sh"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
